language: node_js
node_js: stable

#cache
cache:
  directories:
    - "node_modules"

notifications:
  email:
    recipients:
      - 3075822809@qq.com
    on_success: never
    on_failure: always

# S: Build Lifecycle
install:
  - npm install

before_script:
  - export TZ='Asia/Shanghai'
  - npm install -g gulp 
  - chmod +x _travis.sh

script:
  - hexo g
  - gulp 

after_success:

after_failure:

after_script:
  - ./_travis.sh

# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/shenliyang/shenliyang.github.io.git

