# 头部菜单，title: link
menu:
  Whoami: /about
  Github: https://github.com/quanweiwang
# Twitter: https://twitter.com/FechinLi

# Specify the date when the site was setup
since: 2016

# count values only if the other configs are false
busuanzi_enable: true
# custom uv span for the whole site
busuanzi_site_uv: false
busuanzi_site_uv_header: 本站访客数
busuanzi_site_uv_footer: 人次
# custom pv span for the whole site
busuanzi_site_pv: true
busuanzi_site_pv_header: 本站总访问量
busuanzi_site_pv_footer: 次
# custom pv span for one page only
busuanzi_page_pv: true
busuanzi_page_pv_header: 本文总阅读量
busuanzi_page_pv_footer: 次

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: false

# 默认音乐
mp3: 
  - https://link.hhtjim.com/qq/001T7NTt0GE6RU.mp3
  - https://link.hhtjim.com/qq/002aZAIe1gk8KL.mp3
  - https://link.hhtjim.com/qq/003MNjHn3MgszW.mp3

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover: /img/welcome_cover.jpg

# 默认文章封面图
cover: /img/cover.jpg

# 是否关闭默认滚动条
scrollbar: true

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否自动展开评论框
    autoExpand: true
    # 应用编号
    clientID: '9df2b9438a95189bb534'
    # 应用秘钥
    clientSecret: '149a3805a8ee33d02fadd626cac3e8239c494596'
    # issue仓库名
    repo: 'quanweiwang.github.io'
    # Github名
    owner: 'quanweiwang'
    # Github名
    admin: ['quanweiwang']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: 王权伟

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 

# 网站ico
favicon: /img/avatar.jpg

# rss文件
rss: atom.xml
